# Generated by Django 4.2.7 on 2025-11-01 03:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_courierprofile_address_courierprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available balance (always rounded to 2 decimal places)', max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available balance (always rounded to 2 decimal places)', max_digits=12),
        ),
    ]
