# Generated by Django 4.2.7 on 2025-11-06 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def check_column_exists(cursor, table_name, column_name):
    """Check if a column exists in a table"""
    import django.db
    if django.db.connection.vendor == 'sqlite':
        cursor.execute(f"PRAGMA table_info({table_name})")
        columns = [row[1] for row in cursor.fetchall()]
        return column_name in columns
    
    cursor.execute("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name=%s AND column_name=%s
    """, [table_name, column_name])
    return cursor.fetchone() is not None


def add_fields_safely(apps, schema_editor):
    """Add fields only if they don't exist in the database"""
    db_alias = schema_editor.connection.alias
    connection = schema_editor.connection
    
    # Check database vendor to use appropriate SQL
    vendor = connection.vendor
    
    with connection.cursor() as cursor:
        table_name = 'courier_profiles'
        
        # Check and add each field if it doesn't exist
        fields_to_check = [
            ('account_name', 'VARCHAR(200)'),
            ('approval_notes', 'TEXT'),
            ('approval_status', "VARCHAR(20) DEFAULT 'PENDING'"),
            ('approved_at', 'TIMESTAMP WITH TIME ZONE' if vendor == 'postgresql' else 'TIMESTAMP'),
            ('bank_account_number', 'VARCHAR(20)'),
            ('bank_code', 'VARCHAR(10)'),
            ('bank_name', 'VARCHAR(100)'),
            ('bvn', 'VARCHAR(11)'),
        ]
        
        for field_name, field_type in fields_to_check:
            if not check_column_exists(cursor, table_name, field_name):
                try:
                    # For PostgreSQL, we can use IF NOT EXISTS in newer versions
                    # But for compatibility, we'll check first and then add
                    if vendor == 'postgresql':
                        # PostgreSQL 9.5+ supports IF NOT EXISTS
                        cursor.execute(
                            f'ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS {field_name} {field_type}'
                        )
                    else:
                        # For other databases, check then add
                        cursor.execute(
                            f'ALTER TABLE {table_name} ADD COLUMN {field_name} {field_type}'
                        )
                except Exception as e:
                    # If field exists or error occurs, check if it's a duplicate column error
                    error_msg = str(e).lower()
                    if 'already exists' in error_msg or 'duplicate column' in error_msg:
                        # Field already exists, which is fine - continue
                        pass
                    else:
                        # Some other error - log it
                        import sys
                        print(f"Warning: Could not add {field_name}: {e}", file=sys.stderr)
        
        # Check and add approved_by foreign key if it doesn't exist
        if not check_column_exists(cursor, table_name, 'approved_by_id'):
            try:
                if vendor == 'sqlite':
                    # SQLite supports adding REFERENCES inline during ADD COLUMN
                    cursor.execute(
                        f'ALTER TABLE {table_name} ADD COLUMN approved_by_id INTEGER REFERENCES users(id) ON DELETE SET NULL'
                    )
                elif vendor == 'postgresql':
                    # First add the column
                    cursor.execute(
                        f'ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS approved_by_id INTEGER'
                    )
                    
                    # Then add the foreign key constraint (check if constraint exists first)
                    cursor.execute("""
                        SELECT constraint_name 
                        FROM information_schema.table_constraints 
                        WHERE table_name=%s AND constraint_type='FOREIGN KEY' 
                        AND constraint_name LIKE %s
                    """, [table_name, '%approved_by%'])
                    
                    if not cursor.fetchone():
                        # Constraint doesn't exist, add it
                        cursor.execute(f"""
                            ALTER TABLE {table_name} 
                            ADD CONSTRAINT courier_profiles_approved_by_id_fk 
                            FOREIGN KEY (approved_by_id) 
                            REFERENCES users (id) 
                            ON DELETE SET NULL
                        """)
                else:
                    # Generic fallback
                    cursor.execute(
                        f'ALTER TABLE {table_name} ADD COLUMN approved_by_id INTEGER'
                    )
            except Exception as e:
                error_msg = str(e).lower()
                if 'already exists' in error_msg or 'duplicate' in error_msg:
                    pass
                else:
                    import sys
                    print(f"Warning: Could not add approved_by_id: {e}", file=sys.stderr)


def reverse_add_fields(apps, schema_editor):
    """Reverse migration - remove fields if they exist"""
    # For reverse migration, we'll just pass since these are optional fields
    # In production, you might want to keep the data
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_courierprofile_balance_userprofile_balance'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to handle database and state separately
        migrations.SeparateDatabaseAndState(
            # Database operations - only add fields that don't exist
            database_operations=[
                migrations.RunPython(
                    add_fields_safely,
                    reverse_code=reverse_add_fields,
                    atomic=False
                ),
            ],
            # State operations - update Django's migration state
            state_operations=[
                migrations.AddField(
                    model_name='courierprofile',
                    name='account_name',
                    field=models.CharField(blank=True, help_text='Account holder name', max_length=200, null=True),
                ),
                migrations.AddField(
                    model_name='courierprofile',
                    name='approval_notes',
                    field=models.TextField(blank=True, help_text='Notes from admin regarding approval/rejection', null=True),
                ),
                migrations.AddField(
                    model_name='courierprofile',
                    name='approval_status',
                    field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', help_text='Courier approval status for operations', max_length=20),
                ),
                migrations.AddField(
                    model_name='courierprofile',
                    name='approved_at',
                    field=models.DateTimeField(blank=True, help_text='Date and time when courier was approved', null=True),
                ),
                migrations.AddField(
                    model_name='courierprofile',
                    name='approved_by',
                    field=models.ForeignKey(blank=True, help_text='Admin user who approved the courier', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_couriers', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='courierprofile',
                    name='bank_account_number',
                    field=models.CharField(blank=True, help_text='Bank account number', max_length=20, null=True),
                ),
                migrations.AddField(
                    model_name='courierprofile',
                    name='bank_code',
                    field=models.CharField(blank=True, help_text='Bank code (e.g., from Paystack)', max_length=10, null=True),
                ),
                migrations.AddField(
                    model_name='courierprofile',
                    name='bank_name',
                    field=models.CharField(blank=True, help_text='Bank name', max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='courierprofile',
                    name='bvn',
                    field=models.CharField(blank=True, help_text='Bank Verification Number (11 digits)', max_length=11, null=True),
                ),
            ],
        ),
    ]
