# Generated by Django 4.2.7 on 2025-12-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/products/'),
        ),
    ]
