# Generated by Django 4.2.7 on 2026-01-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_primary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_image',
        ),
    ]
