# Generated by Django 4.2.7 on 2025-11-01 03:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('paystack_recipient_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('recipient_type', models.CharField(choices=[('nuban', 'NUBAN'), ('mobile_money', 'Mobile Money'), ('basa', 'BASA')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer Recipient',
                'verbose_name_plural': 'Transfer Recipients',
                'db_table': 'transfer_recipients',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('DVA', 'Dedicated Virtual Account'), ('USSD', 'USSD'), ('MOBILE_MONEY', 'Mobile Money'), ('PAYSTACK_BALANCE', 'Paystack Balance')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transaction fee', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount after fees (amount - fee)', max_digits=12)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('paystack_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paystack_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_type', models.CharField(choices=[('TRANSACTION_SUCCESS', 'Transaction Success'), ('TRANSACTION_FAILED', 'Transaction Failed'), ('DEPOSIT_RECEIVED', 'Deposit Received'), ('WITHDRAWAL_SUCCESS', 'Withdrawal Success'), ('WITHDRAWAL_FAILED', 'Withdrawal Failed'), ('WITHDRAWAL_REVERSED', 'Withdrawal Reversed'), ('DVA_CREATED', 'DVA Created'), ('BALANCE_LOW', 'Balance Low'), ('TRANSFER_PENDING', 'Transfer Pending'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DedicatedVirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('paystack_customer_id', models.CharField(db_index=True, max_length=255)),
                ('account_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_slug', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dedicated_virtual_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dedicated Virtual Account',
                'verbose_name_plural': 'Dedicated Virtual Accounts',
                'db_table': 'dedicated_virtual_accounts',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type', 'status'], name='transaction_user_id_6c3210_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference'], name='transaction_referen_c33c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['paystack_reference'], name='transaction_paystac_4afc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='transaction_user_id_294647_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_5cf777_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_7336fd_idx'),
        ),
    ]
