# Generated by Django 4.2.7 on 2025-10-31 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.CharField(help_text='The FAQ question (max 500 characters)', max_length=500)),
                ('answer', models.TextField(help_text='Detailed answer to the FAQ question')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('ACCOUNT', 'Account & Profile'), ('ORDERS', 'Orders & Delivery'), ('PAYMENT', 'Payment & Billing'), ('COURIER', 'Courier & Driver'), ('TECHNICAL', 'Technical Support'), ('OTHER', 'Other')], default='GENERAL', help_text='Category to group related FAQs', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first). Use this to manually order FAQs.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faqs',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='faqs_is_acti_7c87ab_idx'), models.Index(fields=['category', 'is_active'], name='faqs_categor_839aa4_idx')],
            },
        ),
    ]
