# Generated by Django 4.2.7 on 2025-10-31 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_email', models.EmailField(help_text='Email address of the requester', max_length=254)),
                ('user_name', models.CharField(blank=True, help_text='Name of the requester', max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20, null=True)),
                ('subject', models.CharField(help_text='Subject/title of the help request', max_length=200)),
                ('message', models.TextField(help_text='Detailed message/description')),
                ('category', models.CharField(choices=[('GENERAL', 'General Inquiry'), ('ACCOUNT', 'Account & Profile'), ('ORDERS', 'Orders & Delivery'), ('PAYMENT', 'Payment & Billing'), ('COURIER', 'Courier & Driver'), ('TECHNICAL', 'Technical Support'), ('OTHER', 'Other')], default='GENERAL', help_text='Category of the help request', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', help_text='Priority level', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='PENDING', help_text='Current status of the request', max_length=20)),
                ('n8n_workflow_triggered', models.BooleanField(default=False, help_text='Whether n8n workflow was successfully triggered')),
                ('n8n_workflow_id', models.CharField(blank=True, help_text='n8n workflow ID or webhook URL used', max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted the request (null if anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Help Request',
                'verbose_name_plural': 'Help Requests',
                'db_table': 'help_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='help_reques_user_id_8172ee_idx'), models.Index(fields=['category', 'status'], name='help_reques_categor_34ac46_idx'), models.Index(fields=['priority', 'status'], name='help_reques_priorit_97f09b_idx'), models.Index(fields=['created_at'], name='help_reques_created_a1fd4c_idx')],
            },
        ),
    ]
